### ISSUE TITLE
Refused to execute script ... because its MIME type ('text/plain') is not executable

### ISSUE THREAD

**Issue by kernc** [kmahelona/ipython_notebook_goodies#1]
Hi,

with the following code block on the top of IPython notebook

``` html
%%html
<h1 id="tocheading">Table of Contents</h1>
<div id="toc"></div>
<script src="https://raw.github.com/kmahelona/ipython_notebook_goodies/master/ipython_notebook_toc.js">
```

I get

> Error: Refused to execute script from 'https://raw.github.com/kmahelona/ipython_notebook_goodies/master/ipython_notebook_toc.js?_=1406989219353' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. 

If you indend to support and maintain this project, you can migrate master banch to [gh-pages](https://help.github.com/articles/user-organization-and-project-pages) branch. Then the address will simply be https://kmahelona.github.com/ipython_notebook_goodies/ipython_notebook_toc.js and it should work.

**Comment by kmahelona** [comment]
Done. Thx for the tip.
