### ISSUE TITLE
ipython_notebook_toc.js doesn't generate toc

### ISSUE THREAD

**Issue by groutr** [kmahelona/ipython_notebook_goodies#3]
Adding the lines

```
<h1 id="tocheading">Table of Contents</h1>
<div id="toc"></div>
<script src="https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js"></script>
```

adds anchors to the notebook headings, but no table of contents is inserted.
I don't know enough of javascript to understand what is going on.
Using the latest IPython notebook (3.2.0)

**Comment by kmahelona** [comment]
It appears that newer versions of iPython Notebook now have some security features which are stripping the javascript: https://ipython.org/ipython-doc/dev/notebook/security.html.

> While never officially supported, it had become common practice to put hidden Javascript or CSS styling in Markdown cells, so that they would not be visible on the page. Since Markdown cells are now sanitized (by Google Caja), all Javascript (including click event handlers, etc.) and CSS will be stripped.

I've changed my notebook to "Trusted" as described at the link but that didn't seem to solve the issue and the JavaScript is still being stripped. I'll have to look further into this.

**Comment by kmahelona** [comment]
To get around the security issue in the latest iPython, you'll have to use the following code to load the script,

```
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')
```

_Thanks to @gparuthi and his fork, https://github.com/gparuthi/ipython_notebook_goodies_
