### ISSUE TITLE
Don't show table of content in ToC

### ISSUE THREAD

**Issue by rpanai** [kmahelona/ipython_notebook_goodies#4]
Hi do you think is possible to don't show the Table of Contents in ToC?

**Comment by kmahelona** [comment]
Can you please elaborate? Do you mean don't show "Table of Contents" or do you mean hide the generated TOC?

**Comment by rpanai** [comment]
Sorry my fault. 
The problem is that as Table of Contents is h1 `<h1 id="tocheading">Table of Contents</h1>` it is then show as a Chapter inside the Table of Contents itself.

**Comment by kmahelona** [comment]
A simple logical to ignore an element with the words “table of contents” or an id “tocheading” could work.

**Comment by kmahelona** [comment]
Looks like that’s in the code, but the id ‘toc’ is used 

https://github.com/kmahelona/ipython_notebook_goodies/blob/aaefb28c21c12237a10f9bd7dff9723feb084391/ipython_notebook_toc.js#L23

**Comment by kmahelona** [comment]
Appears to be implemented. Haven’t tested.
